server:
  port: 9002
spring:
  application:
    name: server
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否注册自身到eureka服务器
    #register-with-eureka: false
    # 是否从eureka上获取注册信息
    #fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka/
