#server:
   #port: 8081
#spring:
  #cloud:
    #bus:   #添加总线配置
     # trace:
       # enabled: true
    #stream:
     # kafka:
       # binder:
         # brokers: http://39.106.59.144:9092
  
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8888
  endpoints:
    web:
      exposure:
        include: '*'


