package com.example.micreoserversimpleprovideruser.dao;

import com.example.micreoserversimpleprovideruser.bean.HygCart;
import com.example.micreoserversimpleprovideruser.bean.HygCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HygCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    long countByExample(HygCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int deleteByExample(HygCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int insert(HygCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int insertSelective(HygCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    List<HygCart> selectByExample(HygCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    HygCart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") HygCart record, @Param("example") HygCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int updateByExample(@Param("record") HygCart record, @Param("example") HygCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(HygCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_cart
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    int updateByPrimaryKey(HygCart record);
}