package com.example.micreoserversimpleprovideruser.bean;

public class HygCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_cart.id_
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_cart.u_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_cart.goods_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_cart.price_count
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Integer priceCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_cart.mprice_count
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Integer mpriceCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_cart.sale_num
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Integer saleNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_cart.id_
     *
     * @return the value of hyg_cart.id_
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_cart.id_
     *
     * @param id the value for hyg_cart.id_
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_cart.u_id
     *
     * @return the value of hyg_cart.u_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_cart.u_id
     *
     * @param uId the value for hyg_cart.u_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_cart.goods_id
     *
     * @return the value of hyg_cart.goods_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_cart.goods_id
     *
     * @param goodsId the value for hyg_cart.goods_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_cart.price_count
     *
     * @return the value of hyg_cart.price_count
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Integer getPriceCount() {
        return priceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_cart.price_count
     *
     * @param priceCount the value for hyg_cart.price_count
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setPriceCount(Integer priceCount) {
        this.priceCount = priceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_cart.mprice_count
     *
     * @return the value of hyg_cart.mprice_count
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Integer getMpriceCount() {
        return mpriceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_cart.mprice_count
     *
     * @param mpriceCount the value for hyg_cart.mprice_count
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setMpriceCount(Integer mpriceCount) {
        this.mpriceCount = mpriceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_cart.sale_num
     *
     * @return the value of hyg_cart.sale_num
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_cart.sale_num
     *
     * @param saleNum the value for hyg_cart.sale_num
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }
}