package com.example.micreoserversimpleprovideruser.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HygOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public HygOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("order_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("order_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeEqualTo(Integer value) {
            addCriterion("order_time =", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotEqualTo(Integer value) {
            addCriterion("order_time <>", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThan(Integer value) {
            addCriterion("order_time >", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_time >=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThan(Integer value) {
            addCriterion("order_time <", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(Integer value) {
            addCriterion("order_time <=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIn(List<Integer> values) {
            addCriterion("order_time in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotIn(List<Integer> values) {
            addCriterion("order_time not in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeBetween(Integer value1, Integer value2) {
            addCriterion("order_time between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("order_time not between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyIsNull() {
            addCriterion("order_money is null");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyIsNotNull() {
            addCriterion("order_money is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyEqualTo(BigDecimal value) {
            addCriterion("order_money =", value, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyNotEqualTo(BigDecimal value) {
            addCriterion("order_money <>", value, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyGreaterThan(BigDecimal value) {
            addCriterion("order_money >", value, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_money >=", value, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyLessThan(BigDecimal value) {
            addCriterion("order_money <", value, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_money <=", value, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyIn(List<BigDecimal> values) {
            addCriterion("order_money in", values, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyNotIn(List<BigDecimal> values) {
            addCriterion("order_money not in", values, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_money between", value1, value2, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andOrderMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_money not between", value1, value2, "orderMoney");
            return (Criteria) this;
        }

        public Criteria andHygNameIsNull() {
            addCriterion("hyg_name is null");
            return (Criteria) this;
        }

        public Criteria andHygNameIsNotNull() {
            addCriterion("hyg_name is not null");
            return (Criteria) this;
        }

        public Criteria andHygNameEqualTo(String value) {
            addCriterion("hyg_name =", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameNotEqualTo(String value) {
            addCriterion("hyg_name <>", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameGreaterThan(String value) {
            addCriterion("hyg_name >", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameGreaterThanOrEqualTo(String value) {
            addCriterion("hyg_name >=", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameLessThan(String value) {
            addCriterion("hyg_name <", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameLessThanOrEqualTo(String value) {
            addCriterion("hyg_name <=", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameLike(String value) {
            addCriterion("hyg_name like", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameNotLike(String value) {
            addCriterion("hyg_name not like", value, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameIn(List<String> values) {
            addCriterion("hyg_name in", values, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameNotIn(List<String> values) {
            addCriterion("hyg_name not in", values, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameBetween(String value1, String value2) {
            addCriterion("hyg_name between", value1, value2, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygNameNotBetween(String value1, String value2) {
            addCriterion("hyg_name not between", value1, value2, "hygName");
            return (Criteria) this;
        }

        public Criteria andHygPhoneIsNull() {
            addCriterion("hyg_phone is null");
            return (Criteria) this;
        }

        public Criteria andHygPhoneIsNotNull() {
            addCriterion("hyg_phone is not null");
            return (Criteria) this;
        }

        public Criteria andHygPhoneEqualTo(String value) {
            addCriterion("hyg_phone =", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneNotEqualTo(String value) {
            addCriterion("hyg_phone <>", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneGreaterThan(String value) {
            addCriterion("hyg_phone >", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("hyg_phone >=", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneLessThan(String value) {
            addCriterion("hyg_phone <", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneLessThanOrEqualTo(String value) {
            addCriterion("hyg_phone <=", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneLike(String value) {
            addCriterion("hyg_phone like", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneNotLike(String value) {
            addCriterion("hyg_phone not like", value, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneIn(List<String> values) {
            addCriterion("hyg_phone in", values, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneNotIn(List<String> values) {
            addCriterion("hyg_phone not in", values, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneBetween(String value1, String value2) {
            addCriterion("hyg_phone between", value1, value2, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPhoneNotBetween(String value1, String value2) {
            addCriterion("hyg_phone not between", value1, value2, "hygPhone");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeIsNull() {
            addCriterion("hyg_postcode is null");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeIsNotNull() {
            addCriterion("hyg_postcode is not null");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeEqualTo(String value) {
            addCriterion("hyg_postcode =", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeNotEqualTo(String value) {
            addCriterion("hyg_postcode <>", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeGreaterThan(String value) {
            addCriterion("hyg_postcode >", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("hyg_postcode >=", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeLessThan(String value) {
            addCriterion("hyg_postcode <", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeLessThanOrEqualTo(String value) {
            addCriterion("hyg_postcode <=", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeLike(String value) {
            addCriterion("hyg_postcode like", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeNotLike(String value) {
            addCriterion("hyg_postcode not like", value, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeIn(List<String> values) {
            addCriterion("hyg_postcode in", values, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeNotIn(List<String> values) {
            addCriterion("hyg_postcode not in", values, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeBetween(String value1, String value2) {
            addCriterion("hyg_postcode between", value1, value2, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygPostcodeNotBetween(String value1, String value2) {
            addCriterion("hyg_postcode not between", value1, value2, "hygPostcode");
            return (Criteria) this;
        }

        public Criteria andHygAddrIsNull() {
            addCriterion("hyg_addr is null");
            return (Criteria) this;
        }

        public Criteria andHygAddrIsNotNull() {
            addCriterion("hyg_addr is not null");
            return (Criteria) this;
        }

        public Criteria andHygAddrEqualTo(String value) {
            addCriterion("hyg_addr =", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrNotEqualTo(String value) {
            addCriterion("hyg_addr <>", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrGreaterThan(String value) {
            addCriterion("hyg_addr >", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrGreaterThanOrEqualTo(String value) {
            addCriterion("hyg_addr >=", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrLessThan(String value) {
            addCriterion("hyg_addr <", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrLessThanOrEqualTo(String value) {
            addCriterion("hyg_addr <=", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrLike(String value) {
            addCriterion("hyg_addr like", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrNotLike(String value) {
            addCriterion("hyg_addr not like", value, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrIn(List<String> values) {
            addCriterion("hyg_addr in", values, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrNotIn(List<String> values) {
            addCriterion("hyg_addr not in", values, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrBetween(String value1, String value2) {
            addCriterion("hyg_addr between", value1, value2, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andHygAddrNotBetween(String value1, String value2) {
            addCriterion("hyg_addr not between", value1, value2, "hygAddr");
            return (Criteria) this;
        }

        public Criteria andOrderStatIsNull() {
            addCriterion("order_stat is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatIsNotNull() {
            addCriterion("order_stat is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatEqualTo(Byte value) {
            addCriterion("order_stat =", value, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatNotEqualTo(Byte value) {
            addCriterion("order_stat <>", value, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatGreaterThan(Byte value) {
            addCriterion("order_stat >", value, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_stat >=", value, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatLessThan(Byte value) {
            addCriterion("order_stat <", value, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatLessThanOrEqualTo(Byte value) {
            addCriterion("order_stat <=", value, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatIn(List<Byte> values) {
            addCriterion("order_stat in", values, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatNotIn(List<Byte> values) {
            addCriterion("order_stat not in", values, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatBetween(Byte value1, Byte value2) {
            addCriterion("order_stat between", value1, value2, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderStatNotBetween(Byte value1, Byte value2) {
            addCriterion("order_stat not between", value1, value2, "orderStat");
            return (Criteria) this;
        }

        public Criteria andOrderExpIsNull() {
            addCriterion("order_exp is null");
            return (Criteria) this;
        }

        public Criteria andOrderExpIsNotNull() {
            addCriterion("order_exp is not null");
            return (Criteria) this;
        }

        public Criteria andOrderExpEqualTo(Byte value) {
            addCriterion("order_exp =", value, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpNotEqualTo(Byte value) {
            addCriterion("order_exp <>", value, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpGreaterThan(Byte value) {
            addCriterion("order_exp >", value, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_exp >=", value, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpLessThan(Byte value) {
            addCriterion("order_exp <", value, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpLessThanOrEqualTo(Byte value) {
            addCriterion("order_exp <=", value, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpIn(List<Byte> values) {
            addCriterion("order_exp in", values, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpNotIn(List<Byte> values) {
            addCriterion("order_exp not in", values, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpBetween(Byte value1, Byte value2) {
            addCriterion("order_exp between", value1, value2, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderExpNotBetween(Byte value1, Byte value2) {
            addCriterion("order_exp not between", value1, value2, "orderExp");
            return (Criteria) this;
        }

        public Criteria andOrderPayIsNull() {
            addCriterion("order_pay is null");
            return (Criteria) this;
        }

        public Criteria andOrderPayIsNotNull() {
            addCriterion("order_pay is not null");
            return (Criteria) this;
        }

        public Criteria andOrderPayEqualTo(Byte value) {
            addCriterion("order_pay =", value, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayNotEqualTo(Byte value) {
            addCriterion("order_pay <>", value, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayGreaterThan(Byte value) {
            addCriterion("order_pay >", value, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_pay >=", value, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayLessThan(Byte value) {
            addCriterion("order_pay <", value, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayLessThanOrEqualTo(Byte value) {
            addCriterion("order_pay <=", value, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayIn(List<Byte> values) {
            addCriterion("order_pay in", values, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayNotIn(List<Byte> values) {
            addCriterion("order_pay not in", values, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayBetween(Byte value1, Byte value2) {
            addCriterion("order_pay between", value1, value2, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderPayNotBetween(Byte value1, Byte value2) {
            addCriterion("order_pay not between", value1, value2, "orderPay");
            return (Criteria) this;
        }

        public Criteria andOrderMesIsNull() {
            addCriterion("order_mes is null");
            return (Criteria) this;
        }

        public Criteria andOrderMesIsNotNull() {
            addCriterion("order_mes is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMesEqualTo(String value) {
            addCriterion("order_mes =", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesNotEqualTo(String value) {
            addCriterion("order_mes <>", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesGreaterThan(String value) {
            addCriterion("order_mes >", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesGreaterThanOrEqualTo(String value) {
            addCriterion("order_mes >=", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesLessThan(String value) {
            addCriterion("order_mes <", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesLessThanOrEqualTo(String value) {
            addCriterion("order_mes <=", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesLike(String value) {
            addCriterion("order_mes like", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesNotLike(String value) {
            addCriterion("order_mes not like", value, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesIn(List<String> values) {
            addCriterion("order_mes in", values, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesNotIn(List<String> values) {
            addCriterion("order_mes not in", values, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesBetween(String value1, String value2) {
            addCriterion("order_mes between", value1, value2, "orderMes");
            return (Criteria) this;
        }

        public Criteria andOrderMesNotBetween(String value1, String value2) {
            addCriterion("order_mes not between", value1, value2, "orderMes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hyg_order
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hyg_order
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}