spring:
 
   
  server:
   port: 8080
  application:
    name: microserver-config-server
  cloud:
   bus:   #添加总线配置
      trace:
        enabled: true
   stream:
      kafka:
        binder:
         brokers: http://39.106.59.144:9092
   config:
      server:      
       git: 
         uri:  https://github.com/Lovelyn921126/spring-cloud-config-repo
         username: Lovelyn921126
         password: a2875372
         repos:
            simple: https://github.com/Lovelyn921126/spring-cloud-config-repo
            special:
              pattern: special*/dev*,*special*/dev*
              uri: https://github.com/Lovelyn921126/specialAAA
              clone-in-start: true
              username: Lovelyn921126
              password: a2875372
            local:
              pattern: local*
              uri: file:/home/configsvc/config-repo
eureka:
  instance:
    hostname: localhost
    metadata-map:
      my-metadat: 我自定义的元数据
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/        
                  
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG              
       
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8889
  endpoints:
    web:
      exposure:
        include: '*'       
              



