spring:
  server:
   port: 8080
  application:
    name: microserver-config-server
  cloud:
    config:
      server:
        health:
           repositories: 
             a-foo: 
              label: master
              name: microservice-foo
              profiles: dev
        git: 
         uri:  https://github.com/Lovelyn921126/spring-cloud-config-repo
         username: Lovelyn921126
         password: a2875372
         repos:
            simple: https://github.com/Lovelyn921126/spring-cloud-config-repo
            special:
              pattern: special*/dev*,*special*/dev*
              uri: https://github.com/Lovelyn921126/specialAAA
              clone-in-start: true
              username: Lovelyn921126
              password: a2875372
            local:
              pattern: local*
              uri: file:/home/configsvc/config-repo
        
                  
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG              
       
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8889
  endpoints:
    web:
      exposure:
        include: '*'       
              



