package com.example.micreoserversimpleprovideruser.bean;

import java.math.BigDecimal;

public class HygOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.user_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_time
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Integer orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_money
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private BigDecimal orderMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.hyg_name
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String hygName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.hyg_phone
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String hygPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.hyg_postcode
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String hygPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.hyg_addr
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String hygAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_stat
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Byte orderStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_exp
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Byte orderExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_pay
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private Byte orderPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_mes
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String orderMes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hyg_order.order_good
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    private String orderGood;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.id
     *
     * @return the value of hyg_order.id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.id
     *
     * @param id the value for hyg_order.id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_id
     *
     * @return the value of hyg_order.order_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_id
     *
     * @param orderId the value for hyg_order.order_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.user_id
     *
     * @return the value of hyg_order.user_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.user_id
     *
     * @param userId the value for hyg_order.user_id
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_time
     *
     * @return the value of hyg_order.order_time
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Integer getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_time
     *
     * @param orderTime the value for hyg_order.order_time
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderTime(Integer orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_money
     *
     * @return the value of hyg_order.order_money
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_money
     *
     * @param orderMoney the value for hyg_order.order_money
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.hyg_name
     *
     * @return the value of hyg_order.hyg_name
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getHygName() {
        return hygName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.hyg_name
     *
     * @param hygName the value for hyg_order.hyg_name
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setHygName(String hygName) {
        this.hygName = hygName == null ? null : hygName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.hyg_phone
     *
     * @return the value of hyg_order.hyg_phone
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getHygPhone() {
        return hygPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.hyg_phone
     *
     * @param hygPhone the value for hyg_order.hyg_phone
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setHygPhone(String hygPhone) {
        this.hygPhone = hygPhone == null ? null : hygPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.hyg_postcode
     *
     * @return the value of hyg_order.hyg_postcode
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getHygPostcode() {
        return hygPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.hyg_postcode
     *
     * @param hygPostcode the value for hyg_order.hyg_postcode
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setHygPostcode(String hygPostcode) {
        this.hygPostcode = hygPostcode == null ? null : hygPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.hyg_addr
     *
     * @return the value of hyg_order.hyg_addr
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getHygAddr() {
        return hygAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.hyg_addr
     *
     * @param hygAddr the value for hyg_order.hyg_addr
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setHygAddr(String hygAddr) {
        this.hygAddr = hygAddr == null ? null : hygAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_stat
     *
     * @return the value of hyg_order.order_stat
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Byte getOrderStat() {
        return orderStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_stat
     *
     * @param orderStat the value for hyg_order.order_stat
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderStat(Byte orderStat) {
        this.orderStat = orderStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_exp
     *
     * @return the value of hyg_order.order_exp
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Byte getOrderExp() {
        return orderExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_exp
     *
     * @param orderExp the value for hyg_order.order_exp
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderExp(Byte orderExp) {
        this.orderExp = orderExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_pay
     *
     * @return the value of hyg_order.order_pay
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public Byte getOrderPay() {
        return orderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_pay
     *
     * @param orderPay the value for hyg_order.order_pay
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderPay(Byte orderPay) {
        this.orderPay = orderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_mes
     *
     * @return the value of hyg_order.order_mes
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getOrderMes() {
        return orderMes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_mes
     *
     * @param orderMes the value for hyg_order.order_mes
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderMes(String orderMes) {
        this.orderMes = orderMes == null ? null : orderMes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hyg_order.order_good
     *
     * @return the value of hyg_order.order_good
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public String getOrderGood() {
        return orderGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hyg_order.order_good
     *
     * @param orderGood the value for hyg_order.order_good
     *
     * @mbg.generated Sun Jan 06 21:43:00 GMT+08:00 2019
     */
    public void setOrderGood(String orderGood) {
        this.orderGood = orderGood == null ? null : orderGood.trim();
    }
}